[[main]]
identifier = "posts"
name = "文章归档"
url = "/posts/"
weight = 1
[main.params]
icon = "fa-solid fa-archive"

[[main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 2
[main.params]
icon = "fa-solid fa-th"

[[main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3
[main.params]
icon = "fa-solid fa-tags"


[[main]]
identifier = "404"
name = "404"
url = "/404/"
weight = 4
[main.params]
icon = ""
