# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]

[footer]
since = 2022
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "✨"
subtitle = "「留存诗意于心，恪守初心于路」"

[article]
math = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
# Widget Search
[[widgets.homepage]]
type = "search"

# Widget Archives
[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

# Widget Categories
[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

# Widget Tag Cloud
[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

# Widget TOC
[[widgets.page]]
type = "toc"

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "AzurIce/azurice.github.io"
repoID = "R_kgDOI7WMeQ"
category = "Giscus"
categoryID = "DIC_kwDOI7WMec4CUE3s"
mapping = "pathname"
strict = 0
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
lang = "zh-CN"

