baseURL = 'http://azurice.github.io/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
title = 'Aoike青之池'
theme = 'FixIt'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]