baseURL = 'http://azurice.github.io/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
title = 'Aoike青之池'
theme = 'FixIt'

# copyright = 'Azur冰弦'
# enableEmoji = false # TODO: try
# enableGitInfo = true # Update the `Lastmod` parameter for each page using the last git commit date
hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]