site_name: Aoike 青池
repo_name: AzurIce/azurice.github.io
repo_url: https://github.com/AzurIce/azurice.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2020 - 2024 AzurIce

dev_addr: 127.0.0.1:9000
use_directory_urls: false

nav:
  - 主页: index.md
  - 博客: blog/index.md
  - 笔记:
    - 主页: notes/index.md
    - 机器学习:
      - 贝叶斯分类: notes/MachineLearning/naive_bayes_classifier.md
      - 决策树: notes/MachineLearning/decision_tree.md
    - 计算机网络:
      - IP 协议: notes/ComputerNetwork/Internet Protocol.md
      - traceroute: notes/ComputerNetwork/traceroute.md
      - TCP 协议: notes/ComputerNetwork/Transmission Control Protocol.md
    - 操作系统:
      - 进程: notes/OperatingSystem/processes.md
      - 主存: notes/OperatingSystem/main-memory.md
    - 项目管理与产品运维:
      - 进度管理:
        - 关键路径法: notes/ProjectManagement/critical-path-methodology.md
        - 挣值分析: notes/ProjectManagement/earned-value-analysis.md
    - 软件测试与质量保证:
      - 黑盒测试: notes/SoftwareTesting/black-box.md
    - 数字图像处理:
      - 傅立叶变换: notes/DigitalImageProcessing/fourier-transform.md


theme:
  icon:
    repo: fontawesome/brands/github
  language: zh
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_javascript:
  # katex
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - _js/katex.js

extra_css:
  - _css/git-commiters.css
  - _css/fonts.css
  - https://unpkg.com/katex@0/dist/katex.min.css # katex

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # Images https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic # critic markup
  - pymdownx.caret # ^^insert^^ ^superscript^
  - pymdownx.mark  # ==mark==
  - pymdownx.tilde # ~~delete~~ ~subscript~
  - pymdownx.keys  # ++key++
  - admonition
  - pymdownx.details # collapsible admonition
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: table
      anchor_linenums: true
  - pymdownx.inlinehilite # `:::language mycode` or `#!language mycode`
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  # Lists
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: diagram
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  # Insider, not available yet
  # - meta
  # TODO: feat social card
  # - social:
  #   concurrency: 4
  - blog:
      archive_toc: true
      categories_toc: true
  - search
  - glightbox # image zoom (mkdocs-glightbox)
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
  - git-revision-date-localized: # (mkdocs-git-revision-date-localized-plugin)
      type: iso_datetime
      enable_creation_date: true
      fallback_to_build_date: true
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
  - git-committers: # (mkdocs-git-committers-plugin-2)
      repository: AzurIce/bjtuse-wiki
      branch: main
  - mermaid2