name: aoike github pages

on:
  push:
    branches: ["aoike"]  # Set a branch that will trigger a deployment
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
      
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
    
      #- name: Git Clone Action
        # You may pin to the exact commit or the version.
        # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      #  uses: sudosubin/git-clone-action@v1.0.1
      #  with:
          # Repository owner and name. Ex: sudosubin/git-clone-action
      #    repository: azurice/aoike
      - run: git config --global user.username "AzurIce"
      - run: git config --global user.email "973562770@qq.com"
      - run: git clone https://github.com/azurice/aoike.git
      
      - run: pip install -e aoike
      
      - uses: actions/checkout@v3
        with:
          ref: aoike
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: 🔨 Aoike Build Site
        run: aioke build

      - name: ⏫ Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: ./site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ☁️ Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.4
